[package]
name = "rts"
version = "0.1.13"
edition = "2021"

[features]
default = ["client"]
client = [
    "dep:bevy",
    "dep:bevy-inspector-egui",
    "dep:bevy_matchbox",
    "dep:getrandom",
    "dep:noise",
    "dep:rand",
]
tracy = ["bevy/trace_tracy"]
tracy_memory = ["tracy", "bevy/trace_tracy_memory"]

[[bin]]
name = "rts"
path = "src/main.rs"
required-features = ["client"]

[dependencies]
bevy = { version = "0.18", features = ["webgpu", "bevy_dev_tools"], optional = true }
bevy-inspector-egui = { version = "0.36", optional = true }
bevy_matchbox = { version = "0.14", features = ["signaling"], optional = true }
noise = { version = "0.9", optional = true }
rand = { version = "0.9", optional = true }
getrandom = { version = "0.3", optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rmp-serde = "1"
uuid = { version = "1", features = ["v4", "serde"] }
game_state = { path = "game_state" }
rusqlite = { version = "0.33", features = ["bundled"] }
bevy_mod_outline = { version = "0.12" }
socket2 = "0.5"
if-addrs = "0.13"
arboard = "3"

[dev-dependencies]

# Enable optimizations for dependencies in dev builds for acceptable framerate
[profile.dev.package."*"]
opt-level = 2

[profile.release]
opt-level = 2
lto = "thin"
codegen-units = 1
strip = true

[profile.profiling]
inherits = "release"
strip = false
debug = 1
